name = "MonolithicFEMVLFS"
uuid = "60e07c00-bbfc-11ec-3291-8bd958d3f92d"
authors = ["Oriol Colomes <oriol.colomes@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
julia = "1.3"
CSV = "0.10.4"
DataFrames = "1.3.2"
DataFramesMeta = "0.10.0"
DrWatson = "2.9.1"
Gridap = "0.17.12"
LaTeXStrings = "1.3.0"
Parameters = "0.12.3"
Plots = "1.27.5"
Roots = "2.0.0"
WriteVTK = "1.14.2"
